# Generated by Django 4.2.7 on 2023-11-28 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 12, 5, 2, 987787)),
        ),
    ]
